set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'sheerun/vim-polyglot'
Plugin 'jiangmiao/auto-pairs'
Plugin 'preservim/nerdtree'
Plugin 'sainnhe/sonokai'

call vundle#end()
filetype plugin indent on

set relativenumber
set shiftwidth=4
set expandtab
set tabstop=4
set incsearch
set hlsearch

color sonokai
nnoremap <C-T> :NERDTree<CR>
